before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: ls -d tests/ZendTest/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-php build/coverage/coverage-{/.}.cov {};' && php vendor/bin/phpcov.php --merge --clover build/logs/clover.xml --whitelist library build/coverage
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["library/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build", "bin", "demos", "resources", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["library/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "bin", "demos", "resources", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["library/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "bin", "demos", "resources", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["library/*", "tests/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["library/*", "tests/*"]
    sensiolabs_security_checker: true
